In [1]:
import pandas as pd
import ipdb

In [2]:
##loading in 15 years of data (same seasons as i used for the premier league data)
#season09=pd.read_csv('data/championship09.csv')
#season10=pd.read_csv('data/championship10.csv')
#season11=pd.read_csv('data/championship11.csv')
#season12=pd.read_csv('data/championship12.csv')
#season13=pd.read_csv('data/championship13.csv')
#season14=pd.read_csv('data/championship14.csv')
#season15=pd.read_csv('data/championship15.csv')
#season16=pd.read_csv('data/championship16.csv')
#season17=pd.read_csv('data/championship17.csv')
#season18=pd.read_csv('data/championship18.csv')
#season19=pd.read_csv('data/championship19.csv')
#season20=pd.read_csv('data/championship20.csv')
#season21=pd.read_csv('data/championship21.csv')
#season22=pd.read_csv('data/championship22.csv')
#season23=pd.read_csv('data/championship23.csv')

In [3]:
#loading in 15 years of data (same seasons as i used for the premier league data)
championship09=pd.read_csv('data/championship09.csv')
championship10=pd.read_csv('data/championship10.csv')
championship11=pd.read_csv('data/championship11.csv')
championship12=pd.read_csv('data/championship12.csv')
championship13=pd.read_csv('data/championship13.csv')
championship14=pd.read_csv('data/championship14.csv')
championship15=pd.read_csv('data/championship15.csv')
championship16=pd.read_csv('data/championship16.csv')
championship17=pd.read_csv('data/championship17.csv')
championship18=pd.read_csv('data/championship18.csv')
championship19=pd.read_csv('data/championship19.csv')
championship20=pd.read_csv('data/championship20.csv')
championship21=pd.read_csv('data/championship21.csv')
championship22=pd.read_csv('data/championship22.csv')
championship23=pd.read_csv('data/championship23.csv')

In [4]:
championship_data = {
    'season09': championship09,
    'season10': championship10,
    'season11': championship11,
    'season12': championship12,
    'season13': championship13,
    'season14': championship14,
    'season15': championship15,
    'season16': championship16,
    'season17': championship17,
    'season18': championship18,
    'season19': championship19,
    'season20': championship20,
    'season21': championship21,
    'season22': championship22,
    'season23': championship23
}

In [5]:
for season_name, season in championship_data.items():
    print(f"{season_name} is length {len(season)}")

season09 is length 552
season10 is length 552
season11 is length 552
season12 is length 552
season13 is length 552
season14 is length 552
season15 is length 552
season16 is length 552
season17 is length 552
season18 is length 552
season19 is length 552
season20 is length 552
season21 is length 552
season22 is length 552
season23 is length 552

In [6]:
23*24

552

In [7]:
matchStats=['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR']

In [8]:
for season_name, season in championship_data.items():
    missing_stats = set(matchStats) - set(season.columns)
    
    if not missing_stats:
        print(f"All match stat columns are in {season_name}")
    else:
        print(f"{len(missing_stats)} match stat columns are missing in {season_name}: {missing_stats}")

All match stat columns are in season09
All match stat columns are in season10
All match stat columns are in season11
1 match stat columns are missing in season12: {'Referee'}
All match stat columns are in season13
All match stat columns are in season14
All match stat columns are in season15
All match stat columns are in season16
All match stat columns are in season17
All match stat columns are in season18
All match stat columns are in season19
All match stat columns are in season20
All match stat columns are in season21
All match stat columns are in season22
All match stat columns are in season23

Referee wont be used, so its not a problem.

In [9]:
matchStats.remove('Referee')

In [10]:
bet365Columns=['B365H','B365D','B365A']

In [11]:
for season_name, season in championship_data.items():
    missing_stats = set(bet365Columns) - set(season.columns)
    
    if not missing_stats:
        print(f"All bet365 odds columns are in {season_name}")
    else:
        print(f"{len(missing_stats)} bet365 odds columns are missing in {season_name}: {missing_stats}")

All bet365 odds columns are in season09
All bet365 odds columns are in season10
All bet365 odds columns are in season11
All bet365 odds columns are in season12
All bet365 odds columns are in season13
All bet365 odds columns are in season14
All bet365 odds columns are in season15
All bet365 odds columns are in season16
All bet365 odds columns are in season17
All bet365 odds columns are in season18
All bet365 odds columns are in season19
All bet365 odds columns are in season20
All bet365 odds columns are in season21
All bet365 odds columns are in season22
All bet365 odds columns are in season23

In [12]:
oldBookieSystem=['BbMxH','BbAvH','BbMxD','BbAvD','BbMxA','BbAvA']
newBookieSystem=['MaxH','AvgH','MaxD','AvgD','MaxA','AvgA']

In [13]:
for season_name, season in championship_data.items():
    if set(oldBookieSystem).issubset(season.columns):
        print(f"All old betting odds columns are in {season_name}")
    elif set(newBookieSystem).issubset(season.columns):
        print(f"All new betting odds columns in {season_name}")
    else:
        print(f"Not all betting odds columns in {season_name}")

All old betting odds columns are in season09
All old betting odds columns are in season10
All old betting odds columns are in season11
All old betting odds columns are in season12
All old betting odds columns are in season13
All old betting odds columns are in season14
All old betting odds columns are in season15
All old betting odds columns are in season16
All old betting odds columns are in season17
All old betting odds columns are in season18
All new betting odds columns in season19
All new betting odds columns in season20
All new betting odds columns in season21
All new betting odds columns in season22
All new betting odds columns in season23

Since 2019/2020 season the data containing the overall market odds changed

from: ['BbMxH','BbAvH','BbMxD','BbAvD','BbMxA','BbAvA']

to: ['MaxH','AvgH','MaxD','AvgA','MaxA','AvgA']

In [14]:
## Mapping bookie systems to seasons
#bookie_systems = {
#    'season09': oldBookieSystem,
#    'season10': oldBookieSystem,
#    'season11': oldBookieSystem,
#    'season12': oldBookieSystem,
#    'season13': oldBookieSystem,
#    'season14': oldBookieSystem,
#    'season15': oldBookieSystem,
#    'season16': oldBookieSystem,
#    'season17': oldBookieSystem,
#    'season18': oldBookieSystem,
#    'season19': newBookieSystem,
#    'season20': newBookieSystem,
#    'season21': newBookieSystem,
#    'season22': newBookieSystem,
#    'season23': newBookieSystem
#}

In [15]:
#season09.loc[:, matchStats + bet365Columns + oldBookieSystem] = season09.loc[:, matchStats + bet365Columns + oldBookieSystem]

In [16]:
#season09=season09.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season10=season10.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season11=season11.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season12=season12.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season13=season13.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season14=season14.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season15=season15.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season16=season16.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season17=season17.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season18=season18.loc[:,matchStats+bet365Columns+oldBookieSystem]
#season19=season19.loc[:,matchStats+bet365Columns+newBookieSystem]
#season20=season20.loc[:,matchStats+bet365Columns+newBookieSystem]
#season21=season21.loc[:,matchStats+bet365Columns+newBookieSystem]
#season22=season22.loc[:,matchStats+bet365Columns+newBookieSystem]
#season23=season23.loc[:,matchStats+bet365Columns+newBookieSystem]

In [17]:
season09 = championship09.loc[:, matchStats + bet365Columns + oldBookieSystem]
season10 = championship10.loc[:, matchStats + bet365Columns + oldBookieSystem]
season11 = championship11.loc[:, matchStats + bet365Columns + oldBookieSystem]
season12 = championship12.loc[:, matchStats + bet365Columns + oldBookieSystem]
season13 = championship13.loc[:, matchStats + bet365Columns + oldBookieSystem]
season14 = championship14.loc[:, matchStats + bet365Columns + oldBookieSystem]
season15 = championship15.loc[:, matchStats + bet365Columns + oldBookieSystem]
season16 = championship16.loc[:, matchStats + bet365Columns + oldBookieSystem]
season17 = championship17.loc[:, matchStats + bet365Columns + oldBookieSystem]
season18 = championship18.loc[:, matchStats + bet365Columns + oldBookieSystem]
season19 = championship19.loc[:, matchStats + bet365Columns + newBookieSystem]
season20 = championship20.loc[:, matchStats + bet365Columns + newBookieSystem]
season21 = championship21.loc[:, matchStats + bet365Columns + newBookieSystem]
season22 = championship22.loc[:, matchStats + bet365Columns + newBookieSystem]
season23 = championship23.loc[:, matchStats + bet365Columns + newBookieSystem]

In [18]:
seasons_data = {
    'season09': season09,
    'season10': season10,
    'season11': season11,
    'season12': season12,
    'season13': season13,
    'season14': season14,
    'season15': season15,
    'season16': season16,
    'season17': season17,
    'season18': season18,
    'season19': season19,
    'season20': season20,
    'season21': season21,
    'season22': season22,
    'season23': season23
}

In [19]:
for season_name, season in seasons_data.items():
    #ipdb.set_trace()
    date_format=season['Date'].apply(lambda x: len(x)).unique()
    if len(date_format)==1:
        if date_format[0]==8:
            season['Date']=pd.to_datetime(season['Date'], format='%d/%m/%y')
            #print(f"successfully updated {season_name}'s date column from '%d/%m/%y'")
            
        elif date_format[0]==10:
            season['Date']=pd.to_datetime(season['Date'], format='%d/%m/%Y')
            #print(f"successfully updated {season_name}'s date column from '%d/%m/%Y'")
        else:
            print(f"unexpected date format, check {season_name}")
    else:
         print(f"more than 1 date format, check {season_name}")

In [20]:
season09['Date']

0     2009-08-07
1     2009-08-08
2     2009-08-08
3     2009-08-08
4     2009-08-08
         ...
547   2010-05-02
548   2010-05-02
549   2010-05-02
550   2010-05-02
551   2010-05-02
Name: Date, Length: 552, dtype: datetime64[ns]

In [21]:
season23

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AR,B365H,B365D,B365A,MaxH,AvgH,MaxD,AvgD,MaxA,AvgA
0,2023-08-04,Sheffield Weds,Southampton,1,2,A,0,1,A,8,...,0,3.10,3.4,2.30,3.31,3.14,3.47,3.38,2.35,2.28
1,2023-08-05,Blackburn,West Brom,2,1,H,2,0,H,12,...,0,2.75,3.3,2.60,2.92,2.78,3.30,3.21,2.72,2.62
2,2023-08-05,Bristol City,Preston,1,1,D,0,0,D,5,...,0,2.05,3.5,3.60,2.15,2.08,3.50,3.39,3.72,3.63
3,2023-08-05,Middlesbrough,Millwall,0,1,A,0,0,D,16,...,0,1.91,3.3,4.33,2.05,1.95,3.60,3.47,4.33,3.97
4,2023-08-05,Norwich,Hull,2,1,H,1,1,D,28,...,0,1.75,3.5,5.00,1.82,1.77,3.75,3.65,5.00,4.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,2024-05-04,Rotherham,Cardiff,5,2,H,2,1,H,16,...,0,3.40,3.4,2.20,3.50,3.40,3.45,3.35,2.23,2.16
548,2024-05-04,Stoke,Bristol City,4,0,H,3,0,H,20,...,0,2.05,3.4,3.75,2.10,2.05,3.70,3.52,3.75,3.51
549,2024-05-04,Sunderland,Sheffield Weds,0,2,A,0,2,A,18,...,0,2.70,3.4,2.55,2.87,2.73,3.40,3.25,2.80,2.62
550,2024-05-04,Swansea,Millwall,0,1,A,0,0,D,9,...,1,2.05,3.5,3.60,2.07,2.04,3.61,3.50,3.76,3.57
551,2024-05-04,West Brom,Preston,3,0,H,1,0,H,16,...,0,1.45,4.2,8.00,1.49,1.45,4.60,4.32,8.00,7.28

In [22]:

for season_name, season in seasons_data.items():
    season.rename(columns={'BbMxH':'MaxH',
                           'BbAvH':'AvgH',
                           'BbMxD':'MaxD',
                           'BbAvD':'AvgD',
                           'BbMxA':'MaxA',
                           'BbAvA':'AvgA'
                          }, inplace=True)

In [23]:
season09

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AR,B365H,B365D,B365A,MaxH,AvgH,MaxD,AvgD,MaxA,AvgA
0,2009-08-07,Middlesbrough,Sheffield United,0,0,D,0,0,D,7,...,0,2.25,3.25,3.20,2.43,2.23,3.40,3.21,3.50,3.13
1,2009-08-08,Cardiff,Scunthorpe,4,0,H,3,0,H,15,...,0,1.67,3.60,5.25,1.73,1.66,3.81,3.48,5.61,5.08
2,2009-08-08,Crystal Palace,Plymouth,1,1,D,0,1,A,16,...,0,1.91,3.30,4.20,1.97,1.88,3.46,3.29,4.48,3.99
3,2009-08-08,Derby,Peterboro,2,1,H,1,0,H,12,...,0,2.00,3.30,3.80,2.10,1.97,3.42,3.27,4.00,3.67
4,2009-08-08,Leicester,Swansea,2,1,H,0,1,A,15,...,0,2.25,3.25,3.20,2.30,2.21,3.31,3.22,3.53,3.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,2010-05-02,Reading,Preston,4,1,H,2,0,H,18,...,0,1.62,3.75,5.50,1.73,1.67,3.90,3.54,6.00,5.00
548,2010-05-02,Scunthorpe,Nott'm Forest,2,2,D,0,2,A,16,...,0,2.80,3.40,2.40,2.90,2.74,3.44,3.28,2.55,2.43
549,2010-05-02,Sheffield Weds,Crystal Palace,2,2,D,1,1,D,13,...,0,2.25,3.40,3.10,2.31,2.24,3.40,3.27,3.41,3.04
550,2010-05-02,Swansea,Doncaster,0,0,D,0,0,D,9,...,0,1.53,3.75,7.00,1.57,1.51,4.13,3.77,7.21,6.43
551,2010-05-02,West Brom,Barnsley,1,1,D,0,0,D,17,...,0,1.40,4.50,7.50,1.44,1.38,4.89,4.30,9.80,7.94

In [24]:
def process_season_data(season_df, season_name):
    # One-hot encode the result field
    ftr_encoded = pd.get_dummies(season_df['FTR'], prefix='', prefix_sep='')
    
    # Adding the new one-hot encoded columns to the dataframe
    season_df = pd.concat([season_df, ftr_encoded], axis=1)
    
    season_df.rename(columns={'H': 'HomeWin', 'D': 'Draw', 'A': 'AwayWin'}, inplace=True)
    
    # Keeping most data except for away team, referee, half-time result, and away cards received by the opposite team.
    homeMatches = season_df[['Date', 'HomeTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
                             'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'HR', 'HomeWin', 'Draw', 'AwayWin']]
    
    homeMatches = homeMatches.copy()
    
    homeMatches.rename(columns={'HomeTeam': 'team',
                                'HomeWin': 'win',
                                'Draw': 'draw',
                                'AwayWin': 'loss',
                                'FTHG': 'goals',
                                'FTAG': 'conceded',
                                'FTR': 'result',
                                'HTHG': 'half_goals',
                                'HTAG': 'half_conceded',
                                'HS': 'shots',
                                'AS': 'shots_against',
                                'HST': 'shots_target',
                                'AST': 'shots_against_target',
                                'HF': 'fouls',
                                'AF': 'fouls_other_team',
                                'HC': 'corners',
                                'AC': 'corners_conceded',
                                'HY': 'yellows',
                                'HR': 'reds'}, inplace=True)

    awayMatches = season_df[['Date', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
                             'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'AY', 'AR', 'HomeWin', 'Draw', 'AwayWin']]

    awayMatches = awayMatches.copy()

    # Same as above but with all the away stats swapped with the home stats
    awayMatches.rename(columns={'AwayTeam': 'team',
                                'AwayWin': 'win',
                                'Draw': 'draw',
                                'HomeWin': 'loss',
                                'FTAG': 'goals',
                                'FTHG': 'conceded',
                                'FTR': 'result',
                                'HTAG': 'half_goals',
                                'HTHG': 'half_conceded',
                                'AS': 'shots',
                                'HS': 'shots_against',
                                'AST': 'shots_target',
                                'HST': 'shots_against_target',
                                'AF': 'fouls',
                                'HF': 'fouls_other_team',
                                'AC': 'corners',
                                'HC': 'corners_conceded',
                                'AY': 'yellows',
                                'AR': 'reds'}, inplace=True)

    awayMatches.reset_index(drop=True)

    # Combine home and away matches
    allMatches = pd.concat([homeMatches, awayMatches], axis=0).sort_values(by=['Date', 'team']).reset_index(drop=True)

    # Add match number and days since previous match
    allMatches['matchNumber'] = allMatches.groupby('team')['Date'].transform('cumcount') + 1
    allMatches['daysSince'] = allMatches.groupby('team')['Date'].transform(lambda x: x - x.shift(1))

    # Define the columns to calculate running totals for
    stats = ['win', 'draw', 'loss', 'goals', 'conceded', 'half_goals', 'half_conceded',
             'shots', 'shots_against', 'shots_target', 'shots_against_target', 'corners',
             'corners_conceded', 'fouls', 'fouls_other_team', 'yellows', 'reds']

    # Loop through the stats and calculate the running totals
    for stat in stats:
        allMatches[f'total.{stat}'] = allMatches.groupby('team')[stat].transform(
            lambda x: x.shift(1).cumsum() / x.shift(1).expanding().count().replace(0, pd.NA)
        )

    # Loop through the stats and calculate the last 3 game averages
    for stat in stats:
        allMatches[f'last3.{stat}'] = allMatches.groupby('team')[stat].transform(
            lambda x: x.shift(1).rolling(window=3, min_periods=1).mean()
        )

    # Drop the original stats columns
    allMatches.drop(columns=['goals', 'conceded', 'result', 'half_goals', 'half_conceded',
                             'shots', 'shots_against', 'shots_target', 'shots_against_target',
                             'fouls', 'fouls_other_team', 'corners', 'corners_conceded', 'yellows',
                             'reds', 'win', 'draw', 'loss'], inplace=True)

    # Merge home and away match data into season DataFrame
    season_df = season_df[['Date', 'HomeTeam', 'AwayTeam', 'FTR', 'AwayWin', 'Draw', 'HomeWin']]

    season_df = season_df.merge(
        allMatches.add_prefix('home.'), how='left', left_on=['Date', 'HomeTeam'], right_on=['home.Date', 'home.team'])

    season_df.drop(columns=['home.Date', 'home.team'], inplace=True)

    season_df = season_df.merge(
        allMatches.add_prefix('away.'), how='left', left_on=['Date', 'AwayTeam'], right_on=['away.Date', 'away.team'])

    season_df.drop(columns=['away.Date', 'away.team'], inplace=True)

    # Home v away performance by team (when home or away respectively)
    season_df['home.total.win.whenHome'] = season_df.groupby('HomeTeam')['HomeWin'].transform(
        lambda x: x.shift(1).cumsum() / x.shift(1).expanding().count().replace(0, pd.NA)
    )

    season_df['home.total.draw.whenHome'] = season_df.groupby('HomeTeam')['Draw'].transform(
        lambda x: x.shift(1).cumsum() / x.shift(1).expanding().count().replace(0, pd.NA)
    )

    season_df['home.total.loss.whenHome'] = season_df.groupby('HomeTeam')['AwayWin'].transform(
        lambda x: x.shift(1).cumsum() / x.shift(1).expanding().count().replace(0, pd.NA)
    )

    season_df['away.total.win.whenAway'] = season_df.groupby('AwayTeam')['AwayWin'].transform(
        lambda x: x.shift(1).cumsum() / x.shift(1).expanding().count().replace(0, pd.NA)
    )

    season_df['away.total.draw.whenAway'] = season_df.groupby('AwayTeam')['Draw'].transform(
        lambda x: x.shift(1).cumsum() / x.shift(1).expanding().count().replace(0, pd.NA)
    )

    season_df['away.total.loss.whenAway'] = season_df.groupby('AwayTeam')['HomeWin'].transform(
        lambda x: x.shift(1).cumsum() / x.shift(1).expanding().count().replace(0, pd.NA)
    )

    # Adding a column to indicate the season
    season_df['season'] = season_name

    return season_df

In [25]:

season09_df = process_season_data(season09, 'season09')
season10_df = process_season_data(season10, 'season10')
season11_df = process_season_data(season11, 'season11')
season12_df = process_season_data(season12, 'season12')
season13_df = process_season_data(season13, 'season13')
season14_df = process_season_data(season14, 'season14')
season15_df = process_season_data(season15, 'season15')
season16_df = process_season_data(season16, 'season16')
season17_df = process_season_data(season17, 'season17')
season18_df = process_season_data(season18, 'season18')
season19_df = process_season_data(season19, 'season19')
season20_df = process_season_data(season20, 'season20')
season21_df = process_season_data(season21, 'season21')
season22_df = process_season_data(season22, 'season22')
season23_df = process_season_data(season23, 'season23')

In [26]:
seasons_df_list = [
    season09_df, season10_df, season11_df, season12_df, season13_df, 
    season14_df, season15_df, season16_df, season17_df, season18_df, 
    season19_df, season20_df, season21_df, season22_df, season23_df
]

In [27]:
seasons_data.keys()

dict_keys(['season09', 'season10', 'season11', 'season12', 'season13', 'season14', 'season15', 'season16', 'season17', 'season18', 'season19', 'season20', 'season21', 'season22', 'season23'])

### Merge all the aggregated match data back with the bookmaker's data

In [28]:
merged_seasons = []
columns_to_merge = ['Date', 'HomeTeam', 'B365H', 'B365D', 'B365A', 'MaxH', 'AvgH', 
                     'MaxD', 'AvgD', 'MaxA', 'AvgA']

In [29]:
for season, book_data in zip(seasons_df_list, seasons_data.values()):
    ##ipdb.set_trace()
    merged_seasons.append(season.merge(book_data[columns_to_merge], how='left', on=['Date', 'HomeTeam']))

In [30]:
seasons_df=pd.concat(merged_seasons,axis=0, ignore_index=True)

In [31]:
seasons_df

,Date,HomeTeam,AwayTeam,FTR,AwayWin,Draw,HomeWin,home.matchNumber,home.daysSince,home.total.win,...,season,B365H,B365D,B365A,MaxH,AvgH,MaxD,AvgD,MaxA,AvgA
0,2009-08-07,Middlesbrough,Sheffield United,D,False,True,False,1,NaT,<NA>,...,season09,2.25,3.25,3.20,2.43,2.23,3.40,3.21,3.50,3.13
1,2009-08-08,Cardiff,Scunthorpe,H,False,False,True,1,NaT,<NA>,...,season09,1.67,3.60,5.25,1.73,1.66,3.81,3.48,5.61,5.08
2,2009-08-08,Crystal Palace,Plymouth,D,False,True,False,1,NaT,<NA>,...,season09,1.91,3.30,4.20,1.97,1.88,3.46,3.29,4.48,3.99
3,2009-08-08,Derby,Peterboro,H,False,False,True,1,NaT,<NA>,...,season09,2.00,3.30,3.80,2.10,1.97,3.42,3.27,4.00,3.67
4,2009-08-08,Leicester,Swansea,H,False,False,True,1,NaT,<NA>,...,season09,2.25,3.25,3.20,2.30,2.21,3.31,3.22,3.53,3.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8275,2024-05-04,Rotherham,Cardiff,H,False,False,True,46,7 days,0.088889,...,season23,3.40,3.40,2.20,3.50,3.40,3.45,3.35,2.23,2.16
8276,2024-05-04,Stoke,Bristol City,H,False,False,True,46,7 days,0.311111,...,season23,2.05,3.40,3.75,2.10,2.05,3.70,3.52,3.75,3.51
8277,2024-05-04,Sunderland,Sheffield Weds,A,True,False,False,46,7 days,0.355556,...,season23,2.70,3.40,2.55,2.87,2.73,3.40,3.25,2.80,2.62
8278,2024-05-04,Swansea,Millwall,A,True,False,False,46,7 days,0.333333,...,season23,2.05,3.50,3.60,2.07,2.04,3.61,3.50,3.76,3.57
8279,2024-05-04,West Brom,Preston,H,False,False,True,46,7 days,0.444444,...,season23,1.45,4.20,8.00,1.49,1.45,4.60,4.32,8.00,7.28

In [32]:
seasons_df.drop(columns=['HomeWin' ,'Draw', 'AwayWin'], inplace=True)

In [33]:
home_columns=[ 'home.daysSince', 'home.total.win',
        'home.total.draw', 'home.total.loss', 'home.total.goals',
        'home.total.conceded', 'home.total.half_goals',
        'home.total.half_conceded', 'home.total.shots',
        'home.total.shots_against', 'home.total.shots_target',
        'home.total.shots_against_target', 'home.total.corners',
        'home.total.corners_conceded', 'home.total.fouls',
        'home.total.fouls_other_team', 'home.total.yellows', 'home.total.reds',
        'home.last3.win', 'home.last3.draw', 'home.last3.loss',
        'home.last3.goals', 'home.last3.conceded', 'home.last3.half_goals',
        'home.last3.half_conceded', 'home.last3.shots',
        'home.last3.shots_against', 'home.last3.shots_target',
        'home.last3.shots_against_target', 'home.last3.corners',
        'home.last3.corners_conceded', 'home.last3.fouls',
        'home.last3.fouls_other_team', 'home.last3.yellows', 'home.last3.reds',
        'home.total.win.whenHome', 'home.total.draw.whenHome',
        'home.total.loss.whenHome'
             ]


home_data = seasons_df.loc[:, home_columns].copy()

In [35]:
away_columns=['away.daysSince', 'away.total.win',
        'away.total.draw', 'away.total.loss', 'away.total.goals',
        'away.total.conceded', 'away.total.half_goals',
        'away.total.half_conceded', 'away.total.shots',
        'away.total.shots_against', 'away.total.shots_target',
        'away.total.shots_against_target', 'away.total.corners',
        'away.total.corners_conceded', 'away.total.fouls',
        'away.total.fouls_other_team', 'away.total.yellows', 'away.total.reds',
        'away.last3.win', 'away.last3.draw', 'away.last3.loss',
        'away.last3.goals', 'away.last3.conceded', 'away.last3.half_goals',
        'away.last3.half_conceded', 'away.last3.shots',
        'away.last3.shots_against', 'away.last3.shots_target',
        'away.last3.shots_against_target', 'away.last3.corners',
        'away.last3.corners_conceded', 'away.last3.fouls',
        'away.last3.fouls_other_team', 'away.last3.yellows', 'away.last3.reds',
        'away.total.win.whenAway', 'away.total.draw.whenAway', 'away.total.loss.whenAway'
             ]

away_data=seasons_df.loc[:,away_columns].copy()

In [36]:
seasons_df.drop(columns=home_columns, inplace=True)
seasons_df.drop(columns=away_columns, inplace=True)

In [38]:
new_column_names=['diff.daysSince', 'diff.total.win',
        'diff.total.draw', 'diff.total.loss', 'diff.total.goals',
        'diff.total.conceded', 'diff.total.half_goals',
        'diff.total.half_conceded', 'diff.total.shots',
        'diff.total.shots_against', 'diff.total.shots_target',
        'diff.total.shots_against_target', 'diff.total.corners',
        'diff.total.corners_conceded', 'diff.total.fouls',
        'diff.total.fouls_other_team', 'diff.total.yellows', 'diff.total.reds',
        'diff.last3.win', 'diff.last3.draw', 'diff.last3.loss',
        'diff.last3.goals', 'diff.last3.conceded', 'diff.last3.half_goals',
        'diff.last3.half_conceded', 'diff.last3.shots',
        'diff.last3.shots_against', 'diff.last3.shots_target',
        'diff.last3.shots_against_target', 'diff.last3.corners',
        'diff.last3.corners_conceded', 'diff.last3.fouls',
        'diff.last3.fouls_other_team', 'diff.last3.yellows', 'diff.last3.reds',
        'diff.total.win.whenHorA', 'diff.total.draw.whenHorA',
        'diff.total.loss.whenHorA'
             ]

In [39]:
diff_df=pd.DataFrame(home_data.values - away_data.values, columns=new_column_names)

In [40]:
seasons_df=pd.concat([seasons_df, diff_df], axis=1)

In [41]:
seasons_df

,Date,HomeTeam,AwayTeam,FTR,home.matchNumber,away.matchNumber,season,B365H,B365D,B365A,...,diff.last3.shots_against_target,diff.last3.corners,diff.last3.corners_conceded,diff.last3.fouls,diff.last3.fouls_other_team,diff.last3.yellows,diff.last3.reds,diff.total.win.whenHorA,diff.total.draw.whenHorA,diff.total.loss.whenHorA
0,2009-08-07,Middlesbrough,Sheffield United,D,1,1,season09,2.25,3.25,3.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>
1,2009-08-08,Cardiff,Scunthorpe,H,1,1,season09,1.67,3.60,5.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>
2,2009-08-08,Crystal Palace,Plymouth,D,1,1,season09,1.91,3.30,4.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>
3,2009-08-08,Derby,Peterboro,H,1,1,season09,2.00,3.30,3.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>
4,2009-08-08,Leicester,Swansea,H,1,1,season09,2.25,3.25,3.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8275,2024-05-04,Rotherham,Cardiff,H,46,46,season23,3.40,3.40,2.20,...,-3.0,-0.666667,3.333333,3.0,-0.666667,2.0,0.0,-0.227273,0.272727,-0.045455
8276,2024-05-04,Stoke,Bristol City,H,46,46,season23,2.05,3.40,3.75,...,0.0,-2.0,1.333333,9.0,-5.666667,1.333333,0.0,0.045455,-0.045455,0.0
8277,2024-05-04,Sunderland,Sheffield Weds,A,46,46,season23,2.70,3.40,2.55,...,-2.0,1.0,-3.666667,1.333333,0.0,0.0,0.0,0.181818,0.045455,-0.227273
8278,2024-05-04,Swansea,Millwall,A,46,46,season23,2.05,3.50,3.60,...,0.0,2.0,-2.666667,-0.333333,3.666667,0.333333,0.0,0.090909,-0.045455,-0.045455
8279,2024-05-04,West Brom,Preston,H,46,46,season23,1.45,4.20,8.00,...,-3.666667,5.0,0.0,-1.0,3.666667,-1.333333,0.333333,0.318182,-0.045455,-0.272727

In [42]:
seasons_df['diff.daysSince']

0         NaT
1         NaT
2         NaT
3         NaT
4         NaT
        ...
8275   0 days
8276   0 days
8277   0 days
8278   0 days
8279   2 days
Name: diff.daysSince, Length: 8280, dtype: timedelta64[ns]

In [44]:
seasons_df['diff.daysSince']=seasons_df['diff.daysSince'].dt.days

In [54]:
seasons_df.to_pickle('data/seasons_betting_df.pkl')

In [53]:
seasons_df[seasons_df['HomeTeam']=='Leeds']

,Date,HomeTeam,AwayTeam,FTR,home.matchNumber,away.matchNumber,season,B365H,B365D,B365A,...,diff.last3.shots_against_target,diff.last3.corners,diff.last3.corners_conceded,diff.last3.fouls,diff.last3.fouls_other_team,diff.last3.yellows,diff.last3.reds,diff.total.win.whenHorA,diff.total.draw.whenHorA,diff.total.loss.whenHorA
558,2010-08-07,Leeds,Derby,A,1,1,season10,2.00,3.30,3.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>
582,2010-08-21,Leeds,Millwall,H,3,3,season10,2.25,3.25,3.20,...,-3.0,-3.0,-0.5,7.5,-1.5,2.0,-0.5,-1.0,0.0,1.0
604,2010-09-11,Leeds,Swansea,H,5,5,season10,2.25,3.25,3.25,...,1.333333,0.0,0.0,6.333333,1.0,0.333333,-0.333333,0.5,0.0,-0.5
641,2010-09-25,Leeds,Sheffield United,H,8,8,season10,2.00,3.30,3.75,...,-1.0,1.0,0.333333,-0.333333,-0.333333,0.666667,0.0,0.333333,-0.333333,0.0
652,2010-09-28,Leeds,Preston,A,9,9,season10,1.73,3.50,5.00,...,-2.333333,0.333333,-2.333333,2.0,-0.666667,0.666667,0.333333,0.5,0.0,-0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8180,2024-03-17,Leeds,Millwall,H,38,38,season23,1.36,5.00,8.50,...,2.333333,3.666667,2.333333,-3.666667,1.666667,-1.0,0.0,0.5,-0.111111,-0.388889
8204,2024-04-01,Leeds,Hull,H,40,39,season23,1.40,5.00,7.50,...,0.666667,1.333333,2.666667,-1.666667,6.0,0.333333,0.0,0.289474,0.04386,-0.333333
8222,2024-04-09,Leeds,Sunderland,D,42,42,season23,1.36,4.75,9.00,...,0.0,1.666667,0.333333,-2.0,2.333333,0.666667,0.0,0.55,-0.05,-0.5
8230,2024-04-13,Leeds,Blackburn,A,43,43,season23,1.33,5.00,10.00,...,-2.0,4.666667,-2.333333,-4.0,4.666667,0.333333,0.0,0.47619,0.047619,-0.52381
8271,2024-05-04,Leeds,Southampton,A,46,46,season23,1.57,4.33,5.50,...,-3.0,2.333333,2.333333,3.666667,-2.666667,-0.333333,0.0,0.272727,-0.045455,-0.227273

In [52]:
seasons_df['HomeTeam'].value_counts()

HomeTeam
Middlesbrough         322
Cardiff               299
Derby                 299
Reading               299
Nott'm Forest         299
Bristol City          299
Birmingham            299
QPR                   276
Millwall              276
Ipswich               253
Sheffield Weds        253
Preston               253
Blackburn             253
Leeds                 253
Hull                  230
Huddersfield          230
Barnsley              230
Watford               207
Norwich               184
Swansea               184
Rotherham             161
Brentford             161
Blackpool             161
Coventry              161
Leicester             138
West Brom             138
Wigan                 138
Fulham                138
Stoke                 138
Brighton              138
Sheffield United      138
Burnley               138
Bolton                138
Charlton              115
Wolves                115
Crystal Palace         92
Bournemouth            92
Peterboro              92
Doncaster              92
Luton                  92
Aston Villa            69
Sunderland             69
Newcastle              46
Plymouth               46
Burton                 46
Southampton            46
Portsmouth             46
Scunthorpe             46
West Ham               23
Yeovil                 23
Milton Keynes Dons     23
Wycombe                23
Name: count, dtype: int64